### ISSUE TITLE
Async publisher

### ISSUE THREAD

**Issue by kozlovic** [softwaremill/mqperf#52]
Disclaimer: I work on NATS Streaming project.

I was surprised by the low numbers for NATS Streaming, so I assumed that you were using synchronous publishers. It turns out, you are not, but using a CountDownLatch every "batchSize" published messages to wait for the acks. The problem is that the max batch size you select is very low (10) and it seems that you actually use a random value between 1..10.
Since it is random, it is possible that some tests are run with 1 while other with 10. Of course, this is per sender, so a given test with say 100 senders will have a median of probably 5. Still, not sure why a random value is used here.

For a very small batch size and the way you are waiting on publish acks, it is possibly less performant than using straight sync publishers. The point of async publisher is to be able to buffer several messages to efficiently fill the outgoing buffer and on the server side minimize socket read calls and file store disk writes (with some messages written at once).

For instance, with the same kind of logic that you are using, but with a batch of 1,000 the NATS Streaming Java client goes from around 17,000 msgs/sec to 130,000 msgs/sec (25 publisher threads, 1 single consumer, no scala, everything running local on a laptop). So as you can see the effect of being able to send more messages asynchronously is huge.

This may not be specific to NATS Streaming and would likely help the other products you are comparing, so overall, I am not saying that the ranking would necessarily changed.

A quick note about message size: note that some products do not offer message compression (NATS Streaming does not), therefore a message of 100 bytes will really result in that amount (actually more since we use protobuf for the envelope). But I believe that Kafka does have compression by default, and size your messages are just "0"'s (if I read the code correctly), it will compress down to almost nothing. Maybe having a message with more random data to be more realistic may be more fair.

Thank you for your attention!

**Comment by adamw** [comment]
Thanks for the remarks!

Regarding the batching - that's how the test is designed, the assumption is that we send messages in random batches of size 1-10 and synchronously wait for acks. That's the same for all queues and tries to somehow (maybe not successfully) reflect a scenario of receiving requests from external clients (e.g. http or grpc) and putting them on the queue, then confirming to the client that the request is handled. So that's simply the premise of the test - same for every queue implementation, described at the beginning of the article. Running the tests with a batch 100 would be a different test (but probably interesting as well).

As we mentioned a couple of times, the goal of the test isn't to somehow measure the absolute performance of NATS or any other queue - as we probably might have used better hardware, bigger batching etc., and probably that's not possible to do properly at all - but only serve as a comparative result.

When writing the client, I roughly followed what's documented in https://github.com/nats-io/stan.java. Do I understand you correctly that using a synchronous `publish` for each message one by one would be more performant than sending in batches, even if they are small (or 5 messages on average)? Btw. I think the `CountDownLatch` approach is also taken from the readme of the java client.

Good point about compression - indeed we are sending only `0`s, and it would be much better to generate random data. I'll add a compression column to the comparison when we do an update in early 2021. I'll also verify if e.g. Kafka changes with random data.

**Comment by kozlovic** [comment]
> Do I understand you correctly that using a synchronous publish for each message one by one would be more performant than sending in batches, even if they are small (or 5 messages on average)?

Not really, but my point was that if the test ends up running with a random batch size of 1, then it is really equivalent of doing a synchronous publish, without the added overhead of the count down latch at the mqperf app level.
But otherwise, no, sync publishers are going to be slower than async publishers, even with a small "batch" size.

Also, I did not read the code properly, I thought the batch size was the same for the duration of the test, which it is not the case, it is picked randomly within the loop, so that's fair.

> Good point about compression - indeed we are sending only 0s, and it would be much better to generate random data. I'll add a compression column to the comparison when we do an update in early 2021. I'll also verify if e.g. Kafka changes with random data.

Thanks. I am closing the issue now.
